=== temp9999gi/projectautomation/source/codegen/Cheetah/_genValueObject2/_doc/genValueObject(참고)/input/gen.dtd
<!ELEMENT class (name,fields,primary-table,join-tables?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT fields (field+)>
<!ELEMENT field (database-field,class-field,type,insert-col?,update-col?,primary-key?)>
<!ELEMENT database-field (#PCDATA)>
<!ELEMENT class-field (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT insert-col EMPTY>
<!ELEMENT update-col EMPTY>
<!ELEMENT primary-key EMPTY>
<!ELEMENT primary-table (#PCDATA)>
<!ELEMENT join-tables (join-table+)>
<!ELEMENT join-table (join-name,clause,left-outer?)>
<!ELEMENT join-name (#PCDATA)>
<!ELEMENT clause (#PCDATA)>
<!ELEMENT left-outer EMPTY>

=== temp9999gi/projectautomation/source/codegen/Cheetah/_genValueObject2/input/Dwarf.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE class SYSTEM "gen.dtd">
<class>
  <name>Account</name>
  <fields>
    <field>
      <database-field>d.user_name</database-field>
      <class-field>username</class-field>
      <type>String</type>
      <primary-key/>
    </field>
    <field>
      <database-field>d.dwarf_name</database-field>
      <class-field>dwarfName</class-field>
      <type>String</type>
      <insert-col/>
      <update-col/>
    </field>
    <field>
      <database-field>d.born</database-field>
      <class-field>born</class-field>
      <type>int</type>
      <insert-col/>
      <update-col/>
    </field>
    <field>
      <database-field>d.home_id</database-field>
      <class-field>homeId</class-field>
      <type>int</type>
      <insert-col/>
      <update-col/>
    </field>
    <field>
      <database-field>m.mountain_name</database-field>
      <class-field>homeName</class-field>
      <type>String</type>
    </field>
    <field>
      <database-field>d.spouse_id</database-field>
      <class-field>spouseId</class-field>
      <type>int</type>
    </field>
    <field>
      <database-field>s.dwarf_name</database-field>
      <class-field>spouseName</class-field>
      <type>String</type>
    </field>
  </fields>
  <primary-table>Account d</primary-table>
  <join-tables>
    <join-table>
      <join-name>Account s</join-name>
      <clause>d.spouse_id = s.dwarf_id</clause>
      <left-outer/>
    </join-table>
    <join-table>
      <join-name>mountain m</join-name>
      <clause>d.home_id = m.mountain_id</clause>
      <left-outer/>
    </join-table>
  </join-tables>
</class>
